# -*- coding: utf-8 -*-
"""ch_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0o1ZgtVd0DwntMCxNlXZ8HplrZ5bOuQ
"""

cd drive/My\ Drive/ML_hw

pwd

import numpy as np
import copy
import random
import matplotlib.pyplot as plt

np.random.seed(0)

from sklearn import datasets
from sklearn.decomposition import PCA

iris = datasets.load_iris() 

x = iris.get('data')
y = iris.get('target')

x

pca = PCA(n_components=2)
pca.fit(x)
print(pca.explained_variance_ratio_)
print(pca.explained_variance_)
X_new1 = pca.transform(x)
plt.scatter(X_new1[:, 0], X_new1[:, 1],marker='o',c=y)  #PCA
plt.show()

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(x,y)
X_new2 = lda.transform(x)
plt.scatter(X_new2[:, 0], X_new2[:, 1],marker='o',c=y)
plt.show()

mean = [20,20]
cov = ([5,0],[25,25])
x1,y1 = np.random.multivariate_normal(mean,cov,10000).T

np.vstack((x1,y1))

plt.figure()
from sklearn import decomposition
ica = decomposition.FastICA()
# X = np.vstack((x,y)).T # 将x，y组成特征矩阵
X_new3 = ica.fit_transform(x)
plt.scatter(X_new3[:,0], X_new3[:,1], c=y)

x

u

fig = plt.figure(figsize=(12, 4))


plt.subplot(131)
plt.scatter(X_new1[:,0], X_new1[:,1], c=y)
plt.title('PCA')
plt.tight_layout()

plt.subplot(132)
plt.scatter(X_new2[:,0], X_new2[:,1], c=y)
plt.title('LDA')
plt.tight_layout()

plt.subplot(133)
plt.scatter(X_new3[:,0], X_new3[:,1], c=y)
plt.title('ICA')
plt.tight_layout()

plt.savefig('8.svg')

